apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-svc
  namespace: {{ .Release.Namespace }}
  labels:
      app: python-app
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80