apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-nginx-cm
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        ports:
          - containerPort: 80
            protocol: TCP
            name: nginx-port
        readinessProbe:
          httpGet:
            path: /index.html
            port: nginx-port
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /index.html
            port: nginx-port
          initialDelaySeconds: 15
          periodSeconds: 20
