apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80